/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestUSDC } from "./TestUSDC";
export * as factories from "./factories";
export { TestUSDC__factory } from "./factories/TestUSDC__factory";
